---
title: "Condition model-scale comparison"
author: "Max Lindmark"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE, cache=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align ='center'
)
```

# Fit condition model with environmental and biological predictors
Fit main model (see exploratory scripts and model comparison), visualize results.

## Load packages

```{r packages, message=FALSE, warning=TRUE}
library(tidyverse)
library(tidylog)
library(viridis)
library(marmap)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(RColorBrewer)
library(gganimate)
library(gifski)
library(latex2exp)
library(patchwork)
library(png)
library(RCurl)
library(wesanderson)
library(qwraps2) 
library(ggcorrplot)
library(ggridges)
# remotes::install_github("pbs-assess/sdmTMB")
library(sdmTMB)
library(mgcv)

# To load entire cache in interactive r session, do: 
# qwraps2::lazyload_cache_dir(path = "R/analysis/condition_model_cf_cache/html")
```

## Read data

```{r read and process data, message=FALSE, warning=FALSE}
# Read the split files and join them
d1 <- readr::read_csv("https://raw.githubusercontent.com/maxlindmark/cod_condition/master/data/for_analysis/mdat_cond_(1_2).csv")
d2 <- readr::read_csv("https://raw.githubusercontent.com/maxlindmark/cod_condition/master/data/for_analysis/mdat_cond_(2_2).csv")

d <- bind_rows(d1, d2)

unique(is.na(d$density_cod))
unique(is.na(d$density_cod_rec))

# Calculate standardized variables
d <- d %>% 
  mutate(ln_length_cm = log(length_cm),
         ln_weight_g = log(weight_g),
         year_ct = year - mean(year),
         biomass_her_sc = biomass_her,
         biomass_her_sd_sc = biomass_her_sd,
         biomass_spr_sc = biomass_spr,
         biomass_spr_sd_sc = biomass_spr_sd,
         density_cod_sc = density_cod,
         density_cod_rec_sc = density_cod_rec,
         density_fle_sc = density_fle,
         density_fle_rec_sc = density_fle_rec,
         density_saduria_sc = density_saduria,
         density_saduria_rec_sc = density_saduria_rec,
         depth_sc = depth,
         depth_rec_sc = depth_rec,
         oxy_sc = oxy,
         oxy_rec_sc = oxy_rec,
         temp_sc = temp,
         temp_rec_sc = temp_rec,
         year_f = as.factor(year))  %>%
  mutate_at(c("biomass_her_sc", "biomass_her_sd_sc", "biomass_spr_sc", "biomass_spr_sd_sc",
              "density_cod_sc", "density_cod_rec_sc", 
              "density_fle_sc", "density_fle_rec_sc", 
              "density_saduria_sc", "density_saduria_rec_sc", 
              "depth_sc", "depth_rec_sc", 
              "oxy_sc", "oxy_rec_sc", 
              "temp_sc", "temp_rec_sc"
              ),
            ~(scale(.) %>% as.vector)) %>% 
  mutate(year = as.integer(year))

unique(is.na(d))

unique(is.na(d$density_cod_rec))
unique(is.na(d$density_cod))
```

Calculate the Fulton condition factor

```{r} 
d$fulton <- (d$weight_g / d$length_cm^3)*100
hist(d$fulton)
```

Calculate annual averages by sd of covariates and le Cren and fit model to annual averages

```{r}
sprat_tot <- d %>% 
  filter(year > 1993 & year < 2015 & !sub_div == 24) %>% 
  distinct(year, sub_div, .keep_all = TRUE) %>% 
  group_by(year) %>% 
  summarise(tot_sprat = sum(biomass_spr_sd))

ggplot(sprat_tot, aes(year, tot_sprat/1000)) +
  geom_point() +
  stat_smooth()

d_sum <- d %>% 
  filter(year > 1993 & year < 2015 & !sub_div == 24 & length_cm < 61 & length_cm > 9) %>% 
  mutate(lngt_class = cut(length_cm, breaks = seq(10, 60, 10))) %>% 
  group_by(year, lngt_class, sub_div) %>% 
  summarise(mean_fulton = mean(fulton)) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  summarise(mean_fulton = mean(mean_fulton)) %>% 
  ungroup()
  
ggplot(d_sum, aes(year, mean_fulton)) +
  geom_point() +
  stat_smooth()

# left_join
d_sum <- left_join(d_sum, sprat_tot)

# scale variables
d_sum <- d_sum %>%
  drop_na(tot_sprat) %>% 
  mutate(tot_sprat_sc = (tot_sprat - mean(tot_sprat)) / sd(tot_sprat))

sd(d_sum$tot_sprat)

# From mich residual plots it seems 1 value per year
m <- gam(mean_fulton ~ 1 + s(tot_sprat_sc, k = 4), data = d_sum)

summary(m)
plot.gam(m)
plot.gam(m, shift = 1)

m2 <- lm(mean_fulton ~ 1 + tot_sprat_sc, data = d_sum)
summary(m2)

m3 <- lm(fulton ~ 1 + biomass_spr_sd_sc, data = d)
summary(m3)

# Ok, effect size of ~0.05 now (compared to 0.01 with raw data). R2 goes from 60% to 0.5%.
```
