---
title: "Condition model - plot parameter estimates of models with and without random effects"
author: "Max Lindmark"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE, cache=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align ='center'
)
```

# Fit condition model with environmental and biological predictors
Fit main model (see exploratory scripts and model comparison), visualize results.

## Load packages

```{r packages, message=FALSE, warning=TRUE}
library(tidyverse)
library(tidylog)
library(viridis)
library(marmap)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(RColorBrewer)
library(gganimate)
library(gifski)
library(latex2exp)
library(patchwork)
library(png)
library(RCurl)
library(wesanderson)
library(qwraps2) 
library(ggcorrplot)
#remotes::install_github("pbs-assess/sdmTMB", ref = "sim2")
library(sdmTMB)

# To load entire cache in interactive r session, do: 
# qwraps2::lazyload_cache_dir(path = "R/supp_analysis/sensitivity_analysis_cf_cache/html")

theme_plot <- function(base_size = 11, base_family = "") {
  theme_light(base_size = base_size, base_family = "") +
    theme(
      axis.text = element_text(size = 9),
      legend.text = element_text(size = 9),
      legend.title = element_text(size = 9),
      legend.position = "bottom",
      legend.key.height = unit(0.2, "cm"),
      legend.margin = margin(0, 0, 0, 0),
      legend.box.margin = margin(-5, -5, -5, -5),
      strip.text = element_text(size = 9, colour = 'gray10', margin = margin(b = 1, t = 1)),
      strip.background = element_rect(fill = "grey95")
      )
}
```

## Read data

```{r read and process data, message=FALSE, warning=FALSE}
# Read the split files and join them
d1 <- readr::read_csv("https://raw.githubusercontent.com/maxlindmark/cod_condition/master/data/for_analysis/mdat_cond_(1_2).csv")
d2 <- readr::read_csv("https://raw.githubusercontent.com/maxlindmark/cod_condition/master/data/for_analysis/mdat_cond_(2_2).csv")

d <- bind_rows(d1, d2)

# Calculate standardized variables
d <- d %>% 
  mutate(ln_length_cm = log(length_cm),
         ln_weight_g = log(weight_g),
         year_ct = year - mean(year),
         biomass_her_sc = biomass_her,
         biomass_her_sd_sc = biomass_her_sd,
         biomass_spr_sc = biomass_spr,
         biomass_spr_sd_sc = biomass_spr_sd,
         density_cod_sc = density_cod,
         density_cod_rec_sc = density_cod_rec,
         density_fle_sc = density_fle,
         density_fle_rec_sc = density_fle_rec,
         density_saduria_sc = density_saduria,
         density_saduria_rec_sc = density_saduria_rec,
         depth_sc = depth,
         depth_rec_sc = depth_rec,
         oxy_sc = oxy,
         oxy_rec_sc = oxy_rec,
         temp_sc = temp,
         temp_rec_sc = temp_rec)  %>%
  mutate_at(c("biomass_her_sc", "biomass_her_sd_sc", "biomass_spr_sc", "biomass_spr_sd_sc",
              "density_cod_sc", "density_cod_rec_sc", 
              "density_fle_sc", "density_fle_rec_sc", 
              "density_saduria_sc", "density_saduria_rec_sc", 
              "depth_sc", "depth_rec_sc",
              "oxy_sc", "oxy_rec_sc",
              "temp_sc", "temp_rec_sc"
              ),
            ~(scale(.) %>% as.vector)) %>% 
  mutate(year = as.integer(year),
         year_f = as.factor(year))

d <- d %>% drop_na(biomass_her_sc, biomass_her_sd_sc, biomass_spr_sc, biomass_spr_sd_sc,
                    density_cod_sc, density_cod_rec_sc, density_fle_sc, density_fle_rec_sc, 
                    density_saduria_sc, density_saduria_rec_sc, depth_sc, depth_rec_sc,
                    oxy_sc, oxy_rec_sc, temp_sc, temp_rec_sc)
```

## Calcualte Le Cren index

```{r calculate Le Cren}
# Coefficients from condition_model_cf
a <- -4.638063
b <- 2.983866
d$weight_g_avg_pred <- exp(a)*d$length_cm^b

d$le_cren <- d$weight_g / d$weight_g_avg_pred

d$log_le_cren <- log(d$le_cren)
hist(d$log_le_cren)
```

```{r make mesh, results='hide', message=FALSE}
spde <- make_mesh(d, xy_cols = c("X", "Y"),
                  n_knots = 100,  
                  type = "kmeans", seed = 42)
```

### Fit main model (without random effects)

```{r spatiotemporal le cren model, cache=TRUE}
ptm <- proc.time()
mfull_ns <- sdmTMB(
  formula = log_le_cren ~ -1 + year_f + biomass_her_sc + biomass_her_sd_sc +
    biomass_spr_sc + biomass_spr_sd_sc +
    density_cod_sc + density_cod_rec_sc + 
    density_fle_sc + density_fle_rec_sc + 
    density_saduria_sc + density_saduria_rec_sc + 
    depth_sc + depth_rec_sc + 
    oxy_sc + oxy_rec_sc + 
    temp_sc + temp_rec_sc,
    data = d,
  time = "year",
  mesh = spde, 
  family = student(link = "identity", df = 5),
  spatiotemporal = "off",
  spatial = "off",
  silent = TRUE,
  reml = FALSE,
  control = sdmTMBcontrol(newton_loops = 1)
  )

system("say Just finished!")
proc.time() - ptm

sanity(mfull_ns)

tidy(mfull_ns, conf.int = TRUE) %>% arrange(desc(abs(estimate)))
tidy(mfull_ns, effects = "ran_par", conf.int = TRUE) 
```

## Plot differences

```{r}
# Extract random and fixed coefficients from the rec model
m_ns <- tidy(mfull_ns, effects = "fixed", conf.int = TRUE) %>%
  filter(!grepl('year', term)) %>% 
  mutate(Model = "Non-spatial")
  
# Read in coefficients from the main model
m_full <- read.csv("https://raw.githubusercontent.com/maxlindmark/cod_condition/master/output/mfull_est.csv") %>%
  dplyr::select(-X) %>% 
  mutate(Model = "Full model")

plot_dat <- bind_rows(m_ns, m_full) %>% mutate(term = as.factor(term))

# Plot effects
# Sort the terms so that random effects are at the top...
plot_dat <- plot_dat %>% 
  mutate(term2 = ifelse(term %in% c("sigma_O", "sigma_E"), 2, 1))

ggplot(plot_dat, aes(reorder(term, term2), estimate, color = Model)) +
  geom_hline(yintercept = 0, linetype = 2, color = "gray40", alpha = 0.5) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0,
                position = position_dodge(width = 0.6), alpha = 0.6) +
  geom_point(size = 2.5, position = position_dodge(width = 0.76), alpha = 0.6) +
  scale_color_brewer(palette = "Dark2") +
  labs(y = "Estimate", x = "Standardized coefficient") +
  scale_x_discrete(breaks = levels(plot_dat$term),
                   labels = c(expression(Herring[rec]),
                              expression(Herring[sub]),
                              expression(Sprat[rec]),
                              expression(Sprat[sub]),
                              expression(Cod[rec]),
                              expression(Cod[haul]),
                              expression(Flounder[rec]),
                              expression(Flounder[haul]),
                              expression(Saduria~entomon[rec]),
                              expression(Saduria~entomon[haul]),
                              expression(Depth[rec]),
                              expression(Depth[haul]),
                              expression(Oxygen[rec]),
                              expression(Oxygen[haul]),
                              expression(sigma[E]),
                              expression(sigma[O]),
                              expression(Temp[rec]),
                              expression(Temp[haul])
                              )) +
  coord_flip() +
  guides(color = guide_legend(ncol = 4)) +
  theme_plot() +
  theme(plot.margin = unit(c(0.4, 0.4, 0.4, 0.4), "cm"),
        legend.position = "bottom") +
  NULL
  
ggsave("figures/supp/condition/sensitivity_spatial_nonspatial_coefs.png", width = 6.5, height = 6.5, dpi = 600)

# 4 / 16 parameters have 

# Just a test to see the labels were alright
effect_sizes <- ggplot(plot_dat, aes(reorder(term, estimate), estimate)) +
  geom_hline(yintercept = 0, linetype = 2, color = "red", alpha = 0.5) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  labs(x = "", y = "Standardized coefficient") +
  coord_flip()
```


