---
title: "Condition model - cross validation"
author: "Max Lindmark, Sean Andersson, Mayya Gogina and Michele Casini"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE, cache=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align ='center'
)
```

# Fit condition model with environmental and biological predictors
Fit main model (see exploratory scripts and model comparison), visualize results.

## Load packages

```{r packages, message=FALSE, warning=TRUE}
library(tidyverse)
library(tidylog)
library(viridis)
library(marmap)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(RColorBrewer)
library(gganimate)
library(gifski)
library(latex2exp)
library(patchwork)
library(png)
library(RCurl)
library(wesanderson)
library(qwraps2) 
library(readxl) 
library(ggcorrplot)
#remotes::install_github("pbs-assess/sdmTMB", ref = "sim2")
library(sdmTMB)

# To load entire cache in interactive r session, do: 
# qwraps2::lazyload_cache_dir(path = "R/analysis/condition_cross_validation_cache/html")
```

## Read data

```{r read and process data, message=FALSE, warning=FALSE}
# Read the split files and join them
d1 <- readr::read_csv("https://raw.githubusercontent.com/maxlindmark/cod_condition/master/data/for_analysis/mdat_cond_(1_2).csv")
d2 <- readr::read_csv("https://raw.githubusercontent.com/maxlindmark/cod_condition/master/data/for_analysis/mdat_cond_(2_2).csv")

d <- bind_rows(d1, d2)

# Calculate standardized variables
d <- d %>% 
  mutate(ln_length_cm = log(length_cm),
         ln_weight_g = log(weight_g),
         year_ct = year - mean(year),
         biomass_her_sc = biomass_her,
         biomass_her_sd_sc = biomass_her_sd,
         biomass_spr_sc = biomass_spr,
         biomass_spr_sd_sc = biomass_spr_sd,
         density_cod_sc = density_cod,
         density_cod_rec_sc = density_cod_rec,
         density_fle_sc = density_fle,
         density_fle_rec_sc = density_fle_rec,
         density_saduria_sc = density_saduria,
         density_saduria_rec_sc = density_saduria_rec,
         depth_sc = depth,
         depth_rec_sc = depth_rec,
         depth_sd_sc = depth_sd,
         oxy_sc = oxy,
         oxy_rec_sc = oxy_rec,
         oxy_sd_sc = oxy_sd,
         temp_sc = temp,
         temp_rec_sc = temp_rec,
         temp_sd_sc = temp_sd)  %>%
  mutate_at(c("biomass_her_sc", "biomass_her_sd_sc", "biomass_spr_sc", "biomass_spr_sd_sc",
              "density_cod_sc", "density_cod_rec_sc", 
              "density_fle_sc", "density_fle_rec_sc", 
              "density_saduria_sc", "density_saduria_rec_sc", 
              "depth_sc", "depth_rec_sc", "depth_sd_sc",
              "oxy_sc", "oxy_rec_sc", "oxy_sd_sc",
              "temp_sc", "temp_rec_sc", "temp_sd_sc"
              ),
            ~(scale(.) %>% as.vector)) %>% 
  mutate(year = as.integer(year))
```

## Add in the oxygen-area variables from Mich

```{r add oxygen area data}
oxy_area <- read_xlsx("data/from_mich/area_vol_1443_1960_2018_oct_nov_20200908.xlsx", sheet = 1) %>% 
  rename("ices_rect" = `ICES-Sq`,
         "year" = "Year") %>% 
  dplyr::select(-SD)

head(oxy_area)

unique(is.na(oxy_area))

oxy_area <- drop_na(oxy_area)

# Now left_join in these variables and scale them
d <- left_join(d, oxy_area)

d <- d %>% 
  mutate(A_43ml_sc = A_43ml,
         A_1ml_sc = A_1ml,
         V_43ml_sc = V_43ml,
         V_1ml_sc = V_1ml)  %>%
  mutate_at(c("A_43ml_sc", "A_1ml_sc", "V_43ml_sc", "V_1ml_sc"),
            ~(scale(.) %>% as.vector))

d <- drop_na(d)
```

## Make spde mesh

```{r make barrier spde mesh, results='hide', cache=TRUE, message=FALSE}
spde <- make_mesh(d, xy_cols = c("X", "Y"),
                  n_knots = 200,  
                  type = "kmeans", seed = 42)
```

## Original model (fitted again because missing 2019)

```{r full model, cache=TRUE}
mfull <- sdmTMB(
  formula = ln_weight_g ~ -1 + ln_length_cm + biomass_her_sc + biomass_her_sd_sc +
    biomass_spr_sc + biomass_spr_sd_sc +
    density_cod_sc + density_cod_rec_sc + 
    density_fle_sc + density_fle_rec_sc + 
    density_saduria_sc + density_saduria_rec_sc + 
    depth_sc + depth_rec_sc + 
    oxy_sc + oxy_rec_sc + 
    temp_sc + temp_rec_sc, 
  time_varying = ~ 1, data = d, time = "year", mesh = spde,
  family = student(link = "identity", df = 5),
  spatiotemporal = "AR1", spatial = "on", silent = TRUE, reml = FALSE,
  control = sdmTMBcontrol(newton_loops = 1, eval.max = 10000, iter.max = 10000, nlminb_loops = 2))
```

## Model with oxygen-area variables

```{r full model with oxygen area variables, cache=TRUE}
mfull2 <- sdmTMB(
  formula = ln_weight_g ~ -1 + ln_length_cm + biomass_her_sc + biomass_her_sd_sc +
    biomass_spr_sc + biomass_spr_sd_sc +
    density_cod_sc + density_cod_rec_sc + 
    density_fle_sc + density_fle_rec_sc + 
    density_saduria_sc + density_saduria_rec_sc + 
    depth_sc + depth_rec_sc + 
    oxy_sc + oxy_rec_sc + 
    temp_sc + temp_rec_sc +
    A_43ml_sc + A_1ml_sc + V_43ml_sc + V_1ml_sc, 
  time_varying = ~ 1, data = d, time = "year", mesh = spde,
  family = student(link = "identity", df = 5),
  spatiotemporal = "AR1", spatial = "on", silent = TRUE, reml = FALSE,
  control = sdmTMBcontrol(newton_loops = 1, eval.max = 10000, iter.max = 10000, nlminb_loops = 2))
```

## Plot coefficients

```{r extract coefficients and plot}
# Extract random and fixed coefficients from the sd25+ model
m_full_est <- bind_rows(tidy(mfull, effects = "ran_par", conf.int = TRUE) %>%
                          filter(term %in% c("sigma_O", "sigma_E")),
                        tidy(mfull, effects = "fixed", conf.int = TRUE) %>%
                          filter(!term %in% c("ln_length_cm"))) %>% 
  mutate(model = "mfull")

# Extract random and fixed coefficients from the rec model
m_full2_est <- bind_rows(tidy(mfull2, effects = "ran_par", conf.int = TRUE) %>%
                           filter(term %in% c("sigma_O", "sigma_E")),
                         tidy(mfull2, effects = "fixed", conf.int = TRUE) %>%
                           filter(!term %in% c("ln_length_cm"))) %>% 
  mutate(model = "mfull with oxygen areas")


plot_dat <- bind_rows(m_full2_est, m_full_est) %>% 
  mutate(term = as.factor(term))

# Plot effects
ggplot(plot_dat, aes(term, estimate, color = model)) +
  geom_hline(yintercept = 0, linetype = 2, color = "gray40", alpha = 0.5) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2,
                position = position_dodge(width = 0.7), alpha = 0.6) +
  geom_point(size = 2.5, position = position_dodge(width = 0.7), alpha = 0.6) +
  scale_color_brewer(palette = "Dark2") +
  labs(x = "", y = "Standardized coefficient") +
  coord_flip() +
  guides(color = guide_legend(ncol = 2)) +
  theme(plot.margin = unit(c(0.4, 0.4, 0.4, 0), "cm"),
        legend.position = "bottom")
  NULL

```



