---
title: "Condition model - cross validation"
author: "Max Lindmark, Sean Andersson, Mayya Gogina and Michele Casini"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE, cache=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 12,
  fig.asp = 0.618,
  fig.align ='center'
)
```

# Fit condition model with environmental and biological predictors
Fit main model (see exploratory scripts and model comparison), visualize results.

## Load packages

```{r packages, message=FALSE, warning=TRUE}
library(tidyverse); theme_set(theme_light(base_size = 12))
library(tidylog)
library(viridis)
library(marmap)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(RColorBrewer)
library(gganimate)
library(gifski)
library(latex2exp)
library(patchwork)
library(png)
library(RCurl)
library(wesanderson)
library(qwraps2) 
library(ggcorrplot)
#remotes::install_github("pbs-assess/sdmTMB", ref = "sim2")
library(sdmTMB)

# To load entire cache in interactive r session, do: 
# qwraps2::lazyload_cache_dir(path = "R/analysis/condition_cross_validation_cache/html")
```

## Read data

```{r read and process data, message=FALSE, warning=FALSE}
# Read the split files and join them
d1 <- readr::read_csv("https://raw.githubusercontent.com/maxlindmark/cod_condition/master/data/for_analysis/mdat_cond_(1_2).csv")
d2 <- readr::read_csv("https://raw.githubusercontent.com/maxlindmark/cod_condition/master/data/for_analysis/mdat_cond_(2_2).csv")

d <- bind_rows(d1, d2)

# Calculate standardized variables
d <- d %>% 
  mutate(ln_length_cm = log(length_cm),
         ln_weight_g = log(weight_g),
         year_ct = year - mean(year),
         biomass_her_sc = biomass_her,
         biomass_her_sd_sc = biomass_her_sd,
         biomass_spr_sc = biomass_spr,
         biomass_spr_sd_sc = biomass_spr_sd,
         density_cod_sc = density_cod,
         density_cod_rec_sc = density_cod_rec,
         density_fle_sc = density_fle,
         density_fle_rec_sc = density_fle_rec,
         density_saduria_sc = density_saduria,
         density_saduria_rec_sc = density_saduria_rec,
         depth_sc = depth,
         depth_rec_sc = depth_rec,
         depth_sd_sc = depth_sd,
         oxy_sc = oxy,
         oxy_rec_sc = oxy_rec,
         oxy_sd_sc = oxy_sd,
         temp_sc = temp,
         temp_rec_sc = temp_rec,
         temp_sd_sc = temp_sd)  %>%
  mutate_at(c("biomass_her_sc", "biomass_her_sd_sc", "biomass_spr_sc", "biomass_spr_sd_sc",
              "density_cod_sc", "density_cod_rec_sc", 
              "density_fle_sc", "density_fle_rec_sc", 
              "density_saduria_sc", "density_saduria_rec_sc", 
              "depth_sc", "depth_rec_sc", "depth_sd_sc",
              "oxy_sc", "oxy_rec_sc", "oxy_sd_sc",
              "temp_sc", "temp_rec_sc", "temp_sd_sc"
              ),
            ~(scale(.) %>% as.vector)) %>% 
  mutate(year = as.integer(year))
```

## Make spde mesh

```{r make barrier spde mesh, results='hide', cache=TRUE, message=FALSE}
spde <- make_mesh(d, xy_cols = c("X", "Y"),
                  n_knots = 200,  
                  type = "kmeans", seed = 42)
```

## CV full model

```{r cv full model, cache=TRUE}
spde <- make_mesh(d, c("X", "Y"),  n_knots = 200,  
                  type = "kmeans", seed = 42)
  
mfull_cv <- sdmTMB_cv(
  formula = ln_weight_g ~ -1 + ln_length_cm + biomass_her_sc + biomass_her_sd_sc +
    biomass_spr_sc + biomass_spr_sd_sc +
    density_cod_sc + density_cod_rec_sc + 
    density_fle_sc + density_fle_rec_sc + 
    density_saduria_sc + density_saduria_rec_sc + 
    depth_sc + depth_rec_sc + 
    oxy_sc + oxy_rec_sc +
    temp_sc + temp_rec_sc, 
  time_varying = ~ 1, data = d, time = "year", mesh = spde,
  family = student(link = "identity", df = 5),
  spatiotemporal = "AR1", spatial = "on", silent = TRUE, reml = FALSE,
  control = sdmTMBcontrol(newton_loops = 1, eval.max = 10000, iter.max = 10000, nlminb_loops = 2),
  k_folds = 5)
  
mfull_cv$fold_elpd
mfull_cv$elpd
 
mfull_cv$fold_loglik
mfull_cv$sum_loglik
 
mfull_cv$max_gradients
```

```{r cv simple model, cache=TRUE}
mfull2_cv <- sdmTMB_cv(
  formula = ln_weight_g ~ -1 + ln_length_cm,
  time_varying = ~ 1, data = d, time = "year", mesh = spde,
  family = student(link = "identity", df = 5),
  spatiotemporal = "AR1", spatial = "on", silent = TRUE, reml = FALSE,
  control = sdmTMBcontrol(newton_loops = 1, eval.max = 10000, iter.max = 10000, nlminb_loops = 2),
  k_folds = 5)
  
mfull2_cv$fold_elpd
mfull2_cv$elpd
 
mfull2_cv$fold_loglik
mfull2_cv$sum_loglik
 
mfull2_cv$max_gradients
```

```{r difference in elpd}
mfull_cv$elpd - mfull2_cv$elpd
```

